### ISSUE TITLE
10-sample ADAM/GATK run

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil-scripts#113]
- [x] @fnothaft: test https://github.com/fnothaft/toil-scripts/tree/no-creds
- [x] @fnothaft: file no-creds PR => #116
- [x] @fnothaft: review Justin's multi-sample script (part of PR #73)
- [x] @hannes-ucsc: merge PR #73
- [x] @hannes-ucsc: merge no-creds PR #116
- [x] @hannes-ucsc: fix https://github.com/BD2KGenomics/cgcloud/issues/101 on cgcloud master
- [ ] ~~@hannes-ucsc: release cgcloud 1.4.0 on master~~ (post-poned)
- [x] @almussel: file überscript PR => #114
- [x] @almussel: finish überscript
- [x] @hannes-ucsc: review überscript PR and merge
- [x] @almussel: add auto-scaling calls to pipeline scripts and file PR
- [x] @hannes-ucsc: release Toil 3.1.4
- [x] @hannes-ucsc: bump toil-box to Toil 3.1.4 in cgcloud master
- [x] @hannes-ucsc: bump toil-box to Toil 3.1.4 in cgcloud 1.3.x
- [x] @fnothaft: review autoscaling PR
- [x] @hannes-ucsc: merge autoscaling PR
- [x] @almussel: install cgcloud 1.4 locally
- [x] @almussel: create head node in root namespace (for runnning überscript), install cgcloud 1.4 on it
- [x] @almussel: create fresh toil-box image in root namespace
- [x] @almussel: create seed cluster
- [x] @almussel: create ~mesosbox/.aws/credentials on leader, drop disposable access/secret key in it
- [ ] @jpdna: Add HG19 to überscript => #132 
- [ ] @jpdna: HG19/10 sample run

**Comment by fnothaft** [comment]
> @fnothaft: test https://github.com/fnothaft/toil-scripts/tree/no-creds

This test is running.

> @fnothaft: review Justin's multi-sample script PR at ???

I have reviewed and tested this and it is included in #73 as https://github.com/fnothaft/toil-scripts/commit/954cb9d871a71613bbaac79469f84c4e8ccd9ce2.

**Comment by hannes-ucsc** [comment]
Add comments like @fnothaft did above. I will incorporate them into the top comment.

**Comment by fnothaft** [comment]
>  @fnothaft: review autoscaling PR

Completed earlier today; waiting for updates from @almussel.

> @fnothaft: test https://github.com/fnothaft/toil-scripts/tree/no-creds

Running.

**Comment by fnothaft** [comment]
> @fnothaft: file PR for https://github.com/fnothaft/toil-scripts/tree/no-creds

https://github.com/BD2KGenomics/toil-scripts/pull/116

**Comment by fnothaft** [comment]
Marked these as resolved:

> @fnothaft: test https://github.com/fnothaft/toil-scripts/tree/no-creds
> @hannes-ucsc: merge no-creds PR #116
> @hannes-ucsc: fix BD2KGenomics/cgcloud#101 on cgcloud master

This is in progress:

> @almussel: finish überscript

This is contained in the überscript PR, so I think we should delete this action item from the ticket (since it is a dupe) or mark it as resolved:

> @almussel: add auto-scaling calls to pipeline scripts and file PR

These two action items should be merged as well:

> @hannes-ucsc: review überscript PR and merge
> @hannes-ucsc: merge autoscaling PR

**Comment by fnothaft** [comment]
Merging #114/#123 will resolve:

> @almussel: finish überscript
> @hannes-ucsc: review überscript PR and merge
> @almussel: add auto-scaling calls to pipeline scripts and file PR
> @hannes-ucsc: merge autoscaling PR

Which will leave us with the following before the major recompute:

> @hannes-ucsc: release cgcloud 1.4.0 on master
> @hannes-ucsc: release Toil 3.1.4
> @hannes-ucsc: bump toil-box to Toil 3.1.4 in cgcloud master and 1.3.x

We'll then satisfy the final few with the recompute:

> @almussel: create head node in root namespace (for runnning überscript), install cgcloud 1.4 on it
> @almussel: create fresh toil-box image in root namespace
> @almussel: create seed cluster
> @almussel: create ~mesosbox/.aws/credentials on leader, drop disposable access/secret key in it

Although, I think our consensus on #114 was to not run in the root namespace.

**Comment by fnothaft** [comment]
Cluster is running in namespace `/adam-sgd/` with cluster name `adam-sgd` and jobstore `adam-sgd-jobstore`.

**Comment by hannes-ucsc** [comment]
>  @hannes-ucsc: release cgcloud 1.4.0 on master

post-poned, we'll be working off of master

>  @hannes-ucsc: release Toil 3.1.4

done

> @hannes-ucsc: bump toil-box to Toil 3.1.4 in cgcloud master and 1.3.x

done for master, added separate entry:

> @hannes-ucsc: bump toil-box to Toil 3.1.4 in cgcloud 1.3.x

**Comment by fnothaft** [comment]
Update on the validation run: all 10 samples have scaled up a node, and are on to alignment.

**Comment by hannes-ucsc** [comment]
Spot instance `i-9bd26143` is not tagged. Security group `fan-test_toil-box` hints at namespace `fan-test` and role `toil-box`. Ok to terminate?

**Comment by fnothaft** [comment]
> Ok to terminate?

Please do; that was from the `--spot-tentative` bug run.

**Comment by fnothaft** [comment]
@jpdna once #132 is complete, you should be able to run the pipeline by following the steps in https://github.com/BD2KGenomics/toil-scripts/blob/master/src/toil_scripts/adam_uberscript/README.md.

**Comment by fnothaft** [comment]
So, not good! Some of the alignment jobs seem to have failed for unknown reasons (logs are missing). I am respawning the cluster and will rerun with workDir deletion disabled.

**Comment by fnothaft** [comment]
OK, relaunched.
